### ISSUE TITLE
[relay] [connection] Unable to convert the connection into 0-RTT

### ISSUE THREAD

**Issue by PHCSJC** [EAimTY/tuic#54]
why this error? thanks!

client：
{
    "relay": {
        "server": "wechat.com",
        "port": 443,
        "token": "TOKEN0",

        "ip": "*.*.*.*",
        "certificates": ["wechat.com.ca.crt"],
        "udp_relay_mode": "native",
        "congestion_controller": "bbr",
        "heartbeat_interval": 10000,
        "alpn": ["h3"],
        "disable_sni": true,
        "reduce_rtt": true,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 1500
    },
    "local": {
        "port": 1080,

        "ip": "0.0.0.0"
    },
    "log_level": "info"
}

server：
{
    "port": 443,
    "token": ["TOKEN0", "TOKEN1"],
    "certificate": "wechat.com.crt",
    "private_key": "wechat.com.key",

    "ip": "0.0.0.0",
    "congestion_controller": "bbr",
    "max_idle_time": 15000,
    "authentication_timeout": 1000,
    "alpn": ["h3"],
    "max_udp_relay_packet_size": 1500,
    "log_level": "info"
}

**Comment by Fhokud** [comment]
复现

**Comment by Fhokud** [comment]
成功复现，客户端和服务端均为0.8.1

**Comment by EAimTY** [comment]
It is totally fine and designed to be like this.

> The basic idea behind 0-RTT connection resumption is that if the client and server had previously established a TLS connection between each other, they can use information cached from that session to establish a new one without having to negotiate the connection’s parameters from scratch. Notably this allows the client to compute the private encryption keys required to protect application data before even talking to the server.
>
> *--[Even faster connection establishment with QUIC 0-RTT resumption](https://blog.cloudflare.com/even-faster-connection-establishment-with-quic-0-rtt-resumption) - Cloudflare*

When the client program starts, trying to convert the very first connection to 0-RTT will always fail because the client has no server-related information yet. This connection handshake  will fall-back to the regular 1-RTT one.

Once the client caches server information from the first connection, any subsequent connection will be convert into a 0-RTT one. That is why you only see this warning message once just after starting the client.

Therefore, you can safely ignore this warn.

**Comment by Fhokud** [comment]
Thanks for answer
